name: tracker_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  postgres: ^3.3.0
  http: ^1.2.0
  fluttertoast: ^8.2.8
  loading_animation_widget:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true